### ISSUE TITLE
Python blockies using old version of Pillow

### ISSUE THREAD

**Issue by damascene** [tristan/blockies#8]
I was trying to install a package but failed because it depends on a recent version of Pillow, while blockies is using much older version.

```
$ poetry add pillow
Using version ^9.5.0 for pillow

Updating dependencies
Resolving dependencies... (0.1s)

Because blockies (0.0.3) depends on Pillow (7.0.0)
 and no versions of blockies match >0.0.3,<0.0.4, blockies (>=0.0.3,<0.0.4) requires Pillow (7.0.0).
So, because as-is depends on both blockies (^0.0.3) and pillow (^9.5.0), version solving failed.
```

Please update it to latest possible Pillow version, Thank you.

**Comment by tristan** [comment]
Now supports being installed with all versions of Pillow >=7 
https://pypi.org/project/blockies/0.0.4/
